### ISSUE TITLE
레이블 생성을 위한 API를 구현한다.

### ISSUE THREAD

**Issue by ahnsoheee** [boostcamp-2020/IssueTracker-7#124]
# 레이블 생성을 위한 API를 구현한다.

|메소드|경로|설명|링크|
|-|-|-|-|
|POST	|api/label|label 생성|[링크](https://github.com/boostcamp-2020/IssueTracker-7/wiki/Label--API#label-%EC%83%9D%EC%84%B1)

## 완료 조건 ✅

- [x] label 을 생성하는 API를 구현한다.

## 관련 이슈 📎

관련 이슈 없음

## 레퍼런스 📚

레퍼런스 없음

**Comment by domino8788** [comment]
위의 커밋을 통해 구현을 완료 했으므로 이슈를 닫는다.
