### ISSUE TITLE
레이블 삭제를 위한 API를 구현한다.

### ISSUE THREAD

**Issue by ahnsoheee** [boostcamp-2020/IssueTracker-7#126]
# 레이블 삭제를 위한 API를 구현한다.

|메소드|경로|설명|링크|
|-|-|-|-|
|DELETE	|api/label/:label_id|label 삭제|[링크](https://github.com/boostcamp-2020/IssueTracker-7/wiki/Label--API#label-%EC%82%AD%EC%A0%9C)

## 완료 조건 ✅

- [x] label을 삭제하는 API를 구현한다.

## 관련 이슈 📎

관련 이슈 없음

## 레퍼런스 📚

레퍼런스 없음

**Comment by domino8788** [comment]
위의 커밋을 통해 구현을 완료 했으므로 수정사항이 발생할 때 까지 이슈를 닫는다.
