### ISSUE TITLE
마일스톤 수정을 위한 API를 구현한다.

### ISSUE THREAD

**Issue by ahnsoheee** [boostcamp-2020/IssueTracker-7#127]
# 마일스톤 수정을 위한 API를 구현한다.

- 마일스톤의 정보와 상태를 수정할 수 있다.

## 완료 조건 ✅

- [x] 마일스톤의 정보를 수정할 수 있다.
- [x] 마일스톤의 상태를 변경할 수 있다.
## 관련 이슈 📎

관련 이슈 없음

## 레퍼런스 📚

레퍼런스 없음

**Comment by domino8788** [comment]
위의 커밋을 통해 구현을 완료 했으므로 수정사항이 발생할 때 까지 이슈를 닫는다.
