### ISSUE TITLE
마일스톤의 삭제를 위한 API를 구현한다.

### ISSUE THREAD

**Issue by ahnsoheee** [boostcamp-2020/IssueTracker-7#128]
# 마일스톤의 삭제를 위한 API를 구현한다.
- 설명1
- 설명2

## 완료 조건 ✅

- [ ] 완료 조건1
- [ ] 완료 조건2
- [ ] 완료 조건3

## 관련 이슈 📎

관련 이슈 없음

## 레퍼런스 📚

레퍼런스 없음

**Comment by domino8788** [comment]
위의 커밋을 통해 구현을 완료 했으므로 수정사항이 발생할 때 까지 이슈를 닫는다.
