### ISSUE TITLE
필터가 적용된 상태에서 필터를 초기화하는 버튼이 생긴다

### ISSUE THREAD

**Issue by ahnsoheee** [boostcamp-2020/IssueTracker-7#20]
# 필터가 적용된 상태에서 필터를 초기화하는 버튼이 생긴다.

## 완료 조건 ✅

- [x] 필터가 적용된 상태일 땐, 다음과 같이 필터 버튼과 목록 사이에 필터를 초기화 할 수 있는 버튼이 생긴다.
- [x] 해당 버튼을 누르면 적용된 필터가 초기화되고 이슈 목록도 원래대로 오픈된 이슈 전체 목록이 나타나게 된다.

## 관련 이슈 📎

관련 이슈 없음

## 레퍼런스 📚

레퍼런스 없음

**Comment by domino8788** [comment]
위의 커밋을 통해 구현을 완료 했으므로 이슈를 닫는다.
