### ISSUE TITLE
Day 15 Scrum

### ISSUE THREAD

**Issue by tksrl0379** [boostcamp-2020/IssueTracker-7#253]
##  스크럼 🏉 

스크럼 템플릿

### 1. 어제 한 일 🌙
- 
### 2. 오늘 할 일 🔥  
- 
### 3. 공유할 이슈 🙌
- 
<hr>

**Comment by ahnsoheee** [comment]
##  스크럼 🏉 

### 1. 어제 한 일 🌙
- 이슈 목록 페이지 구현
- 전체적인 스타일 수정
### 2. 오늘 할 일 🔥
- 데모
- 피어세션
- 마스터클래스
### 3. 공유할 이슈 🙌
-

**Comment by tksrl0379** [comment]
##  스크럼 🏉 

### 1. 어제 한 일 🌙
- 이슈 목록 버그 수정
- 상세 이슈 목록 버그 수정
- 상세 이슈 목록 담당자 수정 기능 추가
### 2. 오늘 할 일 🔥
- 깃헙 정리하기 
- 데모
- 피어세션
- 마스터클래스
### 3. 공유할 이슈 🙌
-

**Comment by domino8788** [comment]
##  스크럼 🏉 

### 1. 어제 한 일 🌙
- 이슈 목록 페이지 구현
- 각 컴포넌트에 필요한 store 구현
- filter 기능 구현
- store 데이터와 컴포넌트 바인딩 구현
- 스타일 수정
### 2. 오늘 할 일 🔥
- master 병합 및 배포
- 데모
- 피어세션
- 마스터클래스

### 3. 공유할 이슈 🙌
-

**Comment by seoulboy** [comment]
##  스크럼 🏉 

### 1. 어제 한 일 🌙

- 카드뷰에서 커멘트 등록
- 카드뷰에서 이슈 상태 바꾸기
- 이슈목록에 반영되지 않는 버그 수정
- 병합


### 2. 오늘 할 일 🔥
- 이슈생성 버튼 이미지 바꾸기
- 저장소 리드미 수정 
- master 병합 및 배포
- 데모
- 피어세션
- 마스터클래스

### 3. 공유할 이슈 🙌
- 오전에 소희님 남진님 얘기하는 틈을 타 스크럼 작성중인데, 두분 꼭 프로젝트 첫날인 것처럼 열심이시네요. 모두 수고 많으셨습니다 🙏
