### ISSUE TITLE
이슈의 상태를 변경하는 API 를 만든다

### ISSUE THREAD

**Issue by tksrl0379** [boostcamp-2020/IssueTracker-7#4]
# 이슈의 상태를 변경하는 API 를 만든다

- 이슈의 상태(title과 status(open, close))를 변경하는 API를 만든다.

## 완료 조건 ✅

- [x] 이슈의 상태를 변경하는 API 를 만든다

## 관련 이슈 📎

관련 이슈 없음

### API 문서
[Issue 수정](https://github.com/boostcamp-2020/IssueTracker-7/wiki/Issue-API#issue-%EC%88%98%EC%A0%95)

**Comment by domino8788** [comment]
구현을 완료 했으므로 수정사항이 발생할 때 까지 이슈를 닫는다.
