### ISSUE TITLE
레이블을 반환하는 API 를 만든다

### ISSUE THREAD

**Issue by tksrl0379** [boostcamp-2020/IssueTracker-7#6]
# 레이블을 반환하는 API 를 만든다
- [Label]필터 클릭 시 전체 레이블 데이터를 가져와야한다.

|메소드|경로|설명|링크|
|-|-|-|-|
|GET	|api/label|전체 label 불러오기|[링크](https://github.com/boostcamp-2020/IssueTracker-7/wiki/Label--API#%EC%A0%84%EC%B2%B4-label-%EB%B6%88%EB%9F%AC%EC%98%A4%EA%B8%B0)
|GET	|api/label/:label_id|단일 label 불러오기|[링크](https://github.com/boostcamp-2020/IssueTracker-7/wiki/Label--API#%EB%8B%A8%EC%9D%BC-label-%EB%B6%88%EB%9F%AC%EC%98%A4%EA%B8%B0)

## 완료 조건 ✅

- [x] 전체 레이블 데이터를 반환한다.
- [x] 단일 레이블 데이터를 반환한다.

## 관련 이슈 📎

관련 이슈 없음

## 레퍼런스 📚

레퍼런스 없음

**Comment by domino8788** [comment]
구현을 완료 했으므로 수정사항이 발생할 때 까지 이슈를 닫는다.
